server:
 port: 8091



spring:
 application:
  name: Api-Gateway.
 cloud:
  gateway:
   routes:
    - id: clg-student
      uri: lb://clg-student
      predicates:
       - Path=/shrclg/**
     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8061/eureka/ 
  instance:
   hostname: localhost
    